CREATE TABLE gymbnb_gyms (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    price INTEGER NOT NULL,
    max_guest INTEGER NOT NULL,
    user_id INTEGER 
        REFERENCES gymbnb_users(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);


